name: ESP Node Microservers CI  

# Controls when the workflow will run
on:
  push:
    branches: [ main, develope ]
  pull_request:
    branches: [ main, develope ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#  We will allow to run the some of the job in parallel 
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node JS
        uses: actions/setup-node@v2
        with: 
          node-version: "18.16.1"
      
      - name: Cache node modules
        id: lint-cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: lint-cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install npm packages
        # Below will prevent to install npm packages if they are installed
        if: steps.lint-cache-nodemodules.outputs.cache-hit != 'true'
        run: npm install

      - name:  Run lint
        run : npm run lint 
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Cache node modules
        id: test-cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: test-cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Use Node JS
        uses: actions/setup-node@v2
        with: 
          node-version: "18.16.1"
      - name: Install npm packages
        # Below will prevent to install npm packages if they are installed
        if: steps.test-cache-nodemodules.outputs.cache-hit != 'true'
        run: npm install
      - name: Run Unit tests with coverage
        run: npm run test:coverage:json_summary
  # We will add more steps with package_check 
  package_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node JS
        uses: actions/setup-node@v2
        with: 
          node-version: "18.16.1"
      - name: Verify same version already exists
        run: echo package_check
      
  build_publish:
    runs-on: ubuntu-latest
    needs: [test, lint, package_check]
    steps:
      - uses: actions/checkout@v2
      # Before use below action will require add seceret variables vaules for ESP_ACR_ENDPOINT, ESP_ACR_USERNAME and ESP_ACR_PASSWORD
      - name: Docker Login 
        run: docker login ${{ secrets.ESP_ACR_ENDPOINT }} -u ${{ secrets.ESP_ACR_USERNAME }} -p ${{ secrets.ESP_ACR_PASSWORD }}
      - name:  Docker build 
        run: |
          export RELEASE_VERSION=$(cat package.json | jq -r .version)
          make container_build
      - name: Docker publish 
        run: |
          export RELEASE_VERSION=$(cat package.json | jq -r .version)
          make container_publish
